nginx:
    image: rmohid/rpi-nginx-workflow:v1
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "81:80"
node1:
    image: rmohid/rpi-node-workflow:v0
    links:
        - redis
    ports:
        - "8080"
node2:
    image: rmohid/rpi-node-workflow:v0
    links:
        - redis
    ports:
        - "8080"
node3:
    image: rmohid/rpi-node-workflow:v0
    links:
        - redis
    ports:
        - "8080"
redis:
    image: rmohid/rpi-redis-workflow:v0
    ports:
        - "6379"
